- hosts: localhost
  pre_tasks:
    - name: Update OS
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/apps.yml
    - include: tasks/dotfiles.yml
